language: c

os:
    - linux

# Use Travis' container-based architecture
sudo: false

addons:
  apt:
    packages:
    - graphviz
    - texlive-latex-extra
    - dvipng

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - TOX_CMD='tox --'
        - TOX_ARGS=''
        # This is the Python version that will be used by the parent conda
        # environment, but it will not be used in the test environments
        # themselves.
        - PYTHON_VERSION=3.6

    matrix:
        # Make sure that installation does not fail
        - TOXENV='py36' TOX_CMD='tox --notest' TOX_ARGS=''
        # Make sure README will display properly on pypi
        - TOXENV='checkdocs'
        - TOXENV='py36'
        - TOXENV='py37'
        # Make sure we haven't broken the build of ASDF Standard docs
        - TOXENV='asdf-standard'

matrix:
    fast_finish: true
    include:

        # Do a coverage test
        - env: TOXENV='coverage' TOX_ARGS=''

        # Perform a sanity check of packaging using twine
        - env: TOXENV='twine' TOX_ARGS=''

        # Do a code style check
        - env: TOXENV='style' TOX_ARGS=''

        # Try a run on OSX
        - os: osx
          env: TOXENV='py37'

        - os: windows
          env: TOXENV='py36'

        - os: windows
          env: TOXENV='py37'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - conda install openssl
    - pip install tox

script:
   - $TOX_CMD $TOX_ARGS
